### ISSUE TITLE
Compiler Error: Imported packages must have the @rbxts scope!

### ISSUE THREAD

**Issue by AlexNolasco** [karikera/rbx-remoteevent#1]
I came across this error and not much documentation about this.

**Comment by karikera** [comment]
Thanks to try to use it!
You can use '@rbxts/remoteevent' package!
https://www.npmjs.com/package/@rbxts/remoteevent
I need to depercate old one :(

Sorry about documentation,  I'm not good at english to write many things..  
I need contributer :(
